Adapted from: https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/hierarchical.ipynb

In [1]:
%pylab --no-import-all inline

from pymc3 import *
import theano.tensor as T
from numpy import random, sum as nsum, ones, concatenate, newaxis, dot, arange
import numpy as np

Populating the interactive namespace from numpy and matplotlib


In [2]:
random.seed(1)

Basic HLM
===

In [3]:
# Set up basic parameters
n_markets = 4
no_permarket = 30
n_observed = no_permarket * n_markets
n_predictors = 3

In [4]:
n_observed

120

In [5]:
# Set up markets
market = concatenate([[i] * no_permarket for i in range(n_markets)])

# Simulate the features
predictors = random.normal(size=(n_observed, n_predictors))

In [6]:
market

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3])

In [7]:
# Choose random values to represent the actual alphas and betas
alpha_a = random.normal(size=(n_markets))
beta_a = random.normal(size=(n_markets, n_predictors))

In [8]:
alpha_a

array([-0.55749472,  0.93916874, -1.94332341,  0.35249436])

In [9]:
beta_a

array([[-0.23643695,  0.7278135 ,  0.51507361],
       [-2.78253447,  0.58464661,  0.32427424],
       [ 0.02186284, -0.46867382,  0.85328122],
       [-0.41302931,  1.83471763,  0.56438286]])

In [10]:
# Calculate the actual data, but put a bit of noise in
y = alpha_a[market] + nsum(beta_a[market] * predictors, 1) + random.normal(size=(n_observed))

In [11]:
y.shape

(120,)

In [12]:
predictors.shape

(120, 3)

In [13]:
# Set up the PyMC model
model = Model()
with model:
    
    # Both alpha and beta are drawn for the same distributions
    mu_alpha = Normal(b"mu_alpha", 0, 10, shape=(1))
    sigma_alpha = Uniform(b"sigma_alpha", .0, 10, testval=2.)
    
    mu_beta = Normal(b"mu_beta", 0, 10, shape=(1))
    sigma_beta = Uniform(b"sigma_beta", .0, 10, testval=2.)
    
    # Simulate the alphas
    alpha = Normal(b"alpha", mu_alpha, sigma_alpha, shape=(n_markets))
    
    # Simulate the betas
    beta = Normal(b'beta', mu_beta, sigma_beta, shape=(n_markets, n_predictors))
    
    m = T.constant(market)
    
    # Simulate the noise
    s = Uniform(b"s", .01, 10, shape=n_markets)

    yd = Normal(b'y', alpha[m] + sum(beta[m] * predictors, 1), s[m] ** -2, observed=y)

    #start = find_MAP()
    #h = find_hessian(start)
    

    #step = Metropolis()
    #step = Slice()
    step = NUTS()

Applied interval-transform to sigma_alpha and added transformed sigma_alpha_interval to model.
Applied interval-transform to sigma_beta and added transformed sigma_beta_interval to model.
Applied interval-transform to s and added transformed s_interval to model.

00001	#include <Python.h>
00002	#include <iostream>
00003	#include "theano_mod_helper.h"
00004	#include <math.h>
00005	#include <numpy/arrayobject.h>
00006	#include <numpy/arrayscalars.h>
00007	#include <vector>
00008	#include <algorithm>
00009	//////////////////////
00010	////  Support Code
00011	//////////////////////
00012	
00013	
00014	    namespace {
00015	    struct __struct_compiled_op_41c56c07f127cf6c730ca19a2313aaab {
00016	        PyObject* __ERROR;
00017	
00018	        PyObject* storage_V3;
00019	PyObject* storage_V5;
00020	PyObject* storage_V7;
00021	PyObject* storage_V9;
00022	PyObject* storage_V11;
00023	PyObject* storage_V13;
00024	PyObject* storage_V15;
00025	PyObject* storage_V17;
00026	PyObject* storage_V19;
00027	PyObject* storage_V21;
00028	PyObject* storage_V23;
00029	PyObject* storage_V25;
00030	PyObject* storage_V27;
00031	PyObject* storage_V29;
00032	PyObject* storage_V31;
00033	PyObject* storage_V33;
00034	PyObject* storage_V35;
00035	PyObject* storage_V37;
000


/tmp/ccWgT58c.s: Assembler messages:
/tmp/ccWgT58c.s:15151: Error: no such instruction: `vfmadd312sd 72(%rsp),%xmm0,%xmm7'
/tmp/ccWgT58c.s:15251: Error: no such instruction: `vfmadd312sd 88(%rsp),%xmm14,%xmm5'




04645	    {Py_XDECREF(py_V45);}
04646	    
04647	double __DUMMY_46;
04648	
04649	}
04650	__label_44:
04651	
04652	        if (V43) {
04653	            Py_XDECREF(V43);
04654	        }
04655	        
04656	    {Py_XDECREF(py_V43);}
04657	    
04658	double __DUMMY_44;
04659	
04660	}
04661	__label_42:
04662	
04663	        if (V41) {
04664	            Py_XDECREF(V41);
04665	        }
04666	        
04667	    {Py_XDECREF(py_V41);}
04668	    
04669	double __DUMMY_42;
04670	
04671	}
04672	__label_40:
04673	
04674	        if (V39) {
04675	            Py_XDECREF(V39);
04676	        }
04677	        
04678	    {Py_XDECREF(py_V39);}
04679	    
04680	double __DUMMY_40;
04681	
04682	}
04683	__label_38:
04684	
04685	        if (V37) {
04686	            Py_XDECREF(V37);
04687	        }
04688	        
04689	    {Py_XDECREF(py_V37);}
04690	    
04691	double __DUMMY_38;
04692	
04693	}
04694	__label_36:
04695	
04696	        if (V35) {
04697	            Py_XDECREF(V35);
04698	        }
04699	        
0470

Exception: ('The following error happened while compiling the node', for{cpu,scan_fn}(Shape_i{0}.0, Subtensor{int64:int64:int8}.0, Shape_i{0}.0, Elemwise{exp,no_inplace}.0, Elemwise{add,no_inplace}.0, Elemwise{mul,no_inplace}.0, Elemwise{sqr,no_inplace}.0, Elemwise{sqr,no_inplace}.0, Elemwise{sqr,no_inplace}.0, Elemwise{sqr,no_inplace}.0, Elemwise{add,no_inplace}.0, Elemwise{Composite{(scalar_sigmoid(i0) * i1)}}.0, Elemwise{Composite{(scalar_sigmoid(i0) * i1)}}.0, Elemwise{sqr,no_inplace}.0, Elemwise{sqr,no_inplace}.0, Alloc.0, Alloc.0, Alloc.0, Elemwise{mul,no_inplace}.0, Elemwise{mul,no_inplace}.0, Alloc.0, Elemwise{mul,no_inplace}.0, Elemwise{Composite{(scalar_sigmoid((-i0)) * i1)}}.0, Elemwise{Composite{(scalar_sigmoid(i0) * scalar_sigmoid((-i0)) * i1)}}.0, Alloc.0, MakeVector{dtype='int64'}.0, Elemwise{Composite{(i0 + (scalar_sigmoid(i1) * scalar_sigmoid(i1) * i2))}}[(0, 0)].0, Elemwise{abs_,no_inplace}.0, Elemwise{sqr,no_inplace}.0, Elemwise{Composite{(Switch((GE(i0, i1) * LE(i0, i2)), i3, i4) + log(i5))}}.0, Sum{acc_dtype=float64}.0, Elemwise{Composite{(Switch((GE(i0, i1) * LE(i0, i2)), i3, i4) + log(i5))}}.0, Elemwise{Composite{(Switch((GE(i0, i1) * LE(i0, i2)), i3, i4) + log(i5))}}.0), '\n', 'The following error happened while compiling the node', Elemwise{Composite{((i0 * i1 * i2) + ((i3 * i1 * i4 * i0) / i5) + (((((-(i6 * i7)) / i8) * i5) + (((-(i6 * i7)) / i8) * i5) + ((-(i9 * i10)) / i11) + ((-(i12 * i4)) / i11)) * i0) + (i3 * ((i9 / i5) + (i13 * i4)) * i0) + (i0 * i1 * i14) + ((i15 * i1 * i16 * i17 * i0) / i11) + (i0 * i1 * i18) + (i0 * i1 * i19) + (((i20 * i21) + (i22 * i23)) * i0) + (i15 * ((Composite{((i0 * i1) + (i2 * i3))}(i24, i0, i6, i25) / i11) + (i26 * i16)) * i17 * i0) + (((i27 * i28) + (i3 * i13 * i17 * i29)) * i0) + (((i6 * i30) + (i6 * i30) + ((i31 * i6 * i32 * i0 * i17 * i5) / i8) + ((i31 * i6 * i32 * i0 * i17 * i5) / i8) + ((((-(i33 * i16)) / i8) + (((-(i34 * i35)) / i36) * i11) + ((-(Composite{((i0 * i1) + (i2 * i3))}(i24, i0, i6, i25) * i37)) / i8) + (((-(i34 * i35)) / i36) * i11)) * i5) + ((i15 * Composite{((i0 * i1) + (i2 * i3))}(i24, i0, i6, i25) * i17) / i11) + ((((-(i33 * i16)) / i8) + (((-(i34 * i35)) / i36) * i11) + ((-(Composite{((i0 * i1) + (i2 * i3))}(i24, i0, i6, i25) * i37)) / i8) + (((-(i34 * i35)) / i36) * i11)) * i5)) * i0) + (i0 * i1 * i38) + (i3 * i13 * i39 * i0) + (((((-(i6 * i39)) / i8) * i5) + ((-(i12 * i39)) / i11) + (((-(i6 * i39)) / i8) * i5)) * i0) + (i0 * i1 * i40))}}(Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, TensorConstant{9.99}, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, TensorConstant{-9.99}, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, TensorConstant{9.99}, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0), '\n', "Compilation failed (return status=1): /tmp/ccWgT58c.s: Assembler messages:. /tmp/ccWgT58c.s:15151: Error: no such instruction: `vfmadd312sd 72(%rsp),%xmm0,%xmm7'. /tmp/ccWgT58c.s:15251: Error: no such instruction: `vfmadd312sd 88(%rsp),%xmm14,%xmm5'. ", '[Elemwise{Composite{((i0 * i1 * i2) + ((i3 * i1 * i4 * i0) / i5) + (((((-(i6 * i7)) / i8) * i5) + (((-(i6 * i7)) / i8) * i5) + ((-(i9 * i10)) / i11) + ((-(i12 * i4)) / i11)) * i0) + (i3 * ((i9 / i5) + (i13 * i4)) * i0) + (i0 * i1 * i14) + ((i15 * i1 * i16 * i17 * i0) / i11) + (i0 * i1 * i18) + (i0 * i1 * i19) + (((i20 * i21) + (i22 * i23)) * i0) + (i15 * ((Composite{((i0 * i1) + (i2 * i3))}(i24, i0, i6, i25) / i11) + (i26 * i16)) * i17 * i0) + (((i27 * i28) + (i3 * i13 * i17 * i29)) * i0) + (((i6 * i30) + (i6 * i30) + ((i31 * i6 * i32 * i0 * i17 * i5) / i8) + ((i31 * i6 * i32 * i0 * i17 * i5) / i8) + ((((-(i33 * i16)) / i8) + (((-(i34 * i35)) / i36) * i11) + ((-(Composite{((i0 * i1) + (i2 * i3))}(i24, i0, i6, i25) * i37)) / i8) + (((-(i34 * i35)) / i36) * i11)) * i5) + ((i15 * Composite{((i0 * i1) + (i2 * i3))}(i24, i0, i6, i25) * i17) / i11) + ((((-(i33 * i16)) / i8) + (((-(i34 * i35)) / i36) * i11) + ((-(Composite{((i0 * i1) + (i2 * i3))}(i24, i0, i6, i25) * i37)) / i8) + (((-(i34 * i35)) / i36) * i11)) * i5)) * i0) + (i0 * i1 * i38) + (i3 * i13 * i39 * i0) + (((((-(i6 * i39)) / i8) * i5) + ((-(i12 * i39)) / i11) + (((-(i6 * i39)) / i8) * i5)) * i0) + (i0 * i1 * i40))}}(<TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, TensorConstant{9.99}, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, TensorConstant{-9.99}, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, TensorConstant{9.99}, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>, <TensorType(float64, scalar)>)]')

In [ ]:
# Actually sample the model
tr = sample(3e4, step, model=model)

In [ ]:
# Plot the variables
traceplot(tr)

In [ ]:
# See a summary
summary(tr)

In [ ]:
alpha_a

In [ ]:
beta_a